[package]
name = "monte_carlo_integration_experiment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rayon = "1.8.0"
rand_pcg = "0.3.1"
approx_eq = "0.1.8"
thread_local = "1.1.7"
